### PR TITLE
Update pages content help: add new article

### PR DESCRIPTION
**Pull request by Mannuel25**
---
name: Add a new article
about: Create your pull request for this project
title: "[PULLS][NEW ARTICLE]"
labels: "Documentation"
assignees: "ProfCyberNaught"
---

<div align="center">
  <a href="https://github.com/ProfCyberNaught">
    ProfCyberNaught of Cybernaught Industries
  </a>
</div>

## Checklist before requesting a review
(remove the space between the brackets and place an 'x' there instead)

- [x] (required) I have performed a `self-review` of my data.
- [x] (required) I have double checked my links use `HTTPS`.
- [x] (required) I have created a `new article file` _(incuding footer table)_.
- [ ] (optional) I have created a `reference section`.
- [x] (required) I have updated the `README.md` file.
- [x] (required) I have added my `profile link` to the `article` file.
- [x] (required) I have added my `profile link` to the `README.md` file.
- [ ] (optional) I used the `blank article template` file.

Required and not optional:
- [x] (required) I agree no `legal copyrights` pass to me by submitting this Pull request.
- [x] (required) I agree to have my `profile link` displayed.
- [x] (required) I agree to the `Code of Conduct`.
- [x] (required) I agree to adhere to the `Contributor documentation`.
- [x] (required) I agree to the `License Terms`.

# About the article you have copied

**Which article have you chosen to copy over?**
Enter article title here: Not Everything is a 'Click Fix'!

**Please provide a link to the article you have copied**

| Article Title | Main Blog Link |
| --- | --- |
| Not Everything is a 'Click Fix'! | [BLOG LINK](https://profcybernaught.hashnode.dev/not-everything-is-a-click-fix)|

**Please tell us the date you copied this article over**
Enter date: Mar 06, 2023

**Did you have any issues when copying over the article from the main website?**
If yes, please enter any issues you had:

**Do we need to implement further changes regarding this request?**
If yes, please provide additional comments:

**Do you feel we need to provide additional documentation regarding this process?**
If yes, please provide us with your additional details considered:

**Additional Information**
If yes, please provide the additional information you would like to include in your pull request:

**Thank you for taking the time to copy an article from the main website over to this repository. Your assistance is very much appreciated.**

### CODE REVIEW

**Review by ProfCyberNaught — COMMENTED** [review]
Thank you Mannuel25 for creating a different pull request with the correct naming for the branch. I can see you have made some changes.

However, I did notice, you had now removed two `<!-- Divider -->` comments from two table rows. Again, these are required as stated in the previous Pull request.

I have added these back into the README.md file, and as you have been completing this article copy task, I have updated a number of files, and created some others too. I have updated the TODO.md file which now forms part of the process to reflect your changes made.

**Review by ProfCyberNaught — APPROVED** [review]
Everything looks good now the comments have been added back in. This can be merged with the main branch.

**Comment by Mannuel25** [comment]
> Thank you Mannuel25 for creating a different pull request with the correct naming for the branch. I can see you have made some changes.
> 
> However, I did notice, you had now removed two `<!-- Divider -->` comments from two table rows. Again, these are required as stated in the previous Pull request.
> 
> I have added these back into the README.md file, and as you have been completing this article copy task, I have updated a number of files, and created some others too. I have updated the TODO.md file which now forms part of the process to reflect your changes made.

Okay, thanks for the corrections.

**Comment by ProfCyberNaught** [comment]
Discovered additional errors in the copy process. These have been updated on the main branch. No link was provided to the main article, and the URL was placed within the Title Tag syntax instead. This resulted in no link being present, and the title tag not being SEO friendly. All corrected. I must have not noticed this when accepting the pull request to begin with after making changes, and reviewing the request.

**Pull request merged**
