### PR TITLE
UpdatePagesContentHelp: add new article

### PR DESCRIPTION
**Pull request by Mannuel25**
---
name: Add a new article
about: Create your pull request for this project
title: "[PULLS][NEW ARTICLE]"
labels: "Documentation"
assignees: "ProfCyberNaught"
---

<div align="center">
  <a href="https://github.com/ProfCyberNaught">
    ProfCyberNaught of Cybernaught Industries
  </a>
</div>

## Checklist before requesting a review
(remove the space between the brackets and place an 'x' there instead)

- [x] (required) I have performed a `self-review` of my data.
- [x] (required) I have double checked my links use `HTTPS`.
- [x] (required) I have created a `new article file` _(incuding footer table)_.
- [ ] (optional) I have created a `reference section`.
- [x] (required) I have updated the `README.md` file.
- [x] (required) I have added my `profile link` to the `article` file.
- [x] (required) I have added my `profile link` to the `README.md` file.
- [ ] (optional) I used the `blank article template` file.

Required and not optional:
- [x] (required) I agree no `legal copyrights` pass to me by submitting this Pull request.
- [x] (required) I agree to have my `profile link` displayed.
- [x] (required) I agree to the `Code of Conduct`.
- [x] (required) I agree to adhere to the `Contributor documentation`.
- [x] (required) I agree to the `License Terms`.

# About the article you have copied

**Which article have you chosen to copy over?**
Enter article title here: Not Everything is a 'Click Fix'!

**Please provide a link to the article you have copied**

| Article Title | Main Blog Link |
| --- | --- |
| Not Everything is a 'Click Fix'! | [BLOG LINK](https://profcybernaught.hashnode.dev/not-everything-is-a-click-fix)|

**Please tell us the date you copied this article over**
Enter date: Mar 06, 2023

**Did you have any issues when copying over the article from the main website?**
If yes, please enter any issues you had:

**Do we need to implement further changes regarding this request?**
If yes, please provide additional comments:

**Do you feel we need to provide additional documentation regarding this process?**
If yes, please provide us with your additional details considered:

**Additional Information**
If yes, please provide the additional information you would like to include in your pull request:

**Thank you for taking the time to copy an article from the main website over to this repository. Your assistance is very much appreciated.**

### CODE REVIEW

**Review by ProfCyberNaught — CHANGES_REQUESTED** [review]
Thank you Mannuel25 for submitting another article copied over from the main cybersecurity blog. I have looked through the submission and can find only three issues moving forward:

**The branch name:**
The branch name must be 'UpdatePagesContentHelp' because this helps the repository owner understand the main reasons for creating the branch and requesting a pull. This is essential to most repositories to establish order, management, organisation, and ease of team contributions. **Your current branch name insinuates you are submitting some form of patch to this repository and this is not the case. This type of branch naming will not be accepted.**

**Comment Divider Missing:**
When using tables within markdown as within the issue, it can become difficult to distinguish between new rows within the table. Therefore, the `<!-- Divider -->` comment is used to help navigate the list of articles within the markdown. This helps those learning to use GitHub to navigate the table rows and understand where one row ends and another one begins. This comment has been removed from the README.md file and must be present.

**Missing Article Tag:**
Within the article document, there should be five tags used. One of them is missing named 'cybersecurity'. I can understand if the article copier is mistaking this to be a repeat. However, the use of a hash '#' refers to different tags within the Hashnode platform. This will need adding.

If these changes are made, your pull request will be accepted.

**Comment by Mannuel25** [comment]
Okay, I will open a new PR to make the necessary changes. Thanks.

**Comment by ProfCyberNaught** [comment]
Needs new pull request and this will now be closed.

**Comment by ProfCyberNaught** [comment]
<ins>**IMPORTANT NOTICE:**</ins> The requirements for contributing to this repository have been updated along with the steps and information relating to it. Please check the new issue: [MAKE AN ARTICLE COPY ISSUE](https://github.com/ProfCyberNaught/cybersecurity-blog-posts/issues/43 "MAKE AN ARTICLE COPY ISSUE - ProfCyberNaught - Cybersecurity Blog")

**Pull request closed without merging**
